
const K="devtrack_pro_v2",S="devtrack_session_v2",$=id=>document.getElementById(id),all=s=>[...document.querySelectorAll(s)];
const seed={users:[
{id:"U1",name:"Kevin Figueroa",email:"admin@devtrack.local",password:"admin123",role:"Administrador",active:true},
{id:"U2",name:"Ana Martínez",email:"tecnico@devtrack.local",password:"tecnico123",role:"Técnico",active:true},
{id:"U3",name:"Carlos López",email:"usuario@devtrack.local",password:"usuario123",role:"Usuario",active:true}],
categories:[{id:"C1",name:"Hardware",description:"Equipos y periféricos"},{id:"C2",name:"Software",description:"Aplicaciones y sistemas"},{id:"C3",name:"Redes",description:"Internet y conectividad"},{id:"C4",name:"Accesos",description:"Usuarios y permisos"}],
tickets:[
{id:"TK-1001",title:"Equipo de caja sin Internet",description:"El equipo perdió conexión a la red. Otros dispositivos sí tienen acceso.",category:"Redes",priority:"Alta",status:"En progreso",requester:"U3",assigned:"U2",created:"2026-09-03T08:20:00",updated:"2026-09-05T09:15:00",comments:[{user:"U2",text:"Se revisará cableado y configuración IP.",date:"2026-09-05T09:15:00"}],history:[{user:"U3",text:"Ticket creado",date:"2026-09-03T08:20:00"},{user:"U2",text:"Estado cambiado a En progreso",date:"2026-09-05T09:15:00"}]},
{id:"TK-1002",title:"Instalación de software contable",description:"Se requiere instalar el software autorizado en una nueva computadora.",category:"Software",priority:"Media",status:"Abierto",requester:"U3",assigned:"",created:"2026-09-04T11:30:00",updated:"2026-09-04T11:30:00",comments:[],history:[{user:"U3",text:"Ticket creado",date:"2026-09-04T11:30:00"}]},
{id:"TK-1003",title:"Cambio de contraseña",description:"El usuario no puede ingresar al sistema interno.",category:"Accesos",priority:"Baja",status:"Resuelto",requester:"U3",assigned:"U2",created:"2026-09-01T14:05:00",updated:"2026-09-02T10:10:00",comments:[],history:[{user:"U3",text:"Ticket creado",date:"2026-09-01T14:05:00"},{user:"U2",text:"Estado cambiado a Resuelto",date:"2026-09-02T10:10:00"}]}]};
let data=JSON.parse(localStorage.getItem(K)||JSON.stringify(seed)),me=null,selected=null;
const save=()=>localStorage.setItem(K,JSON.stringify(data)),user=id=>data.users.find(x=>x.id===id),now=()=>new Date().toISOString(),fmt=x=>new Intl.DateTimeFormat("es-SV",{dateStyle:"medium",timeStyle:"short"}).format(new Date(x)),esc=x=>String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
function toast(t){$("toast").textContent=t;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),1800)}
function vis(){return me.role==="Administrador"?data.tickets:me.role==="Técnico"?data.tickets.filter(t=>!t.assigned||t.assigned===me.id):data.tickets.filter(t=>t.requester===me.id)}
function badge(v,type){let c=type==="status"?{"Abierto":"open","Asignado":"assigned","En progreso":"progress","Resuelto":"resolved","Cerrado":"closed"}[v]:{"Baja":"low","Media":"medium","Alta":"high","Crítica":"critical"}[v];return `<span class="badge ${c}">${esc(v)}</span>`}
function showApp(){ $("login").classList.add("hidden");$("app").classList.remove("hidden");$("who").textContent=me.name;$("role").textContent=me.role;all(".admin").forEach(x=>x.classList.toggle("hidden",me.role!=="Administrador"));all(".staff").forEach(x=>x.classList.toggle("hidden",me.role==="Usuario"));renderOptions();renderAll();nav("dashboard")}
function nav(v){all(".view").forEach(x=>x.classList.add("hidden"));$(v+"View").classList.remove("hidden");all("nav button").forEach(x=>x.classList.toggle("active",x.dataset.view===v));let m={dashboard:["Dashboard","Resumen general"],tickets:["Tickets","Gestión de incidencias"],users:["Usuarios","Cuentas y roles"],categories:["Categorías","Clasificación de incidencias"],reports:["Reportes","Indicadores y exportación"]}[v];$("title").textContent=m[0];$("subtitle").textContent=m[1]}
function renderAll(){renderDashboard();renderTickets();renderUsers();renderCategories();renderReports()}
function bars(id,vals,field){let t=vis(),mx=Math.max(1,...vals.map(v=>t.filter(x=>x[field]===v).length));$(id).innerHTML=vals.map(v=>{let n=t.filter(x=>x[field]===v).length;return `<div class="bar"><span>${v}</span><div class="track"><div class="fill" style="width:${n/mx*100}%"></div></div><b>${n}</b></div>`}).join("")}
function renderDashboard(){let t=vis(),n=s=>t.filter(x=>x.status===s).length;$("sTotal").textContent=t.length;$("sOpen").textContent=n("Abierto")+n("Asignado");$("sProgress").textContent=n("En progreso");$("sDone").textContent=n("Resuelto")+n("Cerrado");bars("statusBars",["Abierto","Asignado","En progreso","Resuelto","Cerrado"],"status");bars("priorityBars",["Baja","Media","Alta","Crítica"],"priority");let a=t.flatMap(x=>x.history.map(h=>({...h,id:x.id,title:x.title}))).sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,7);$("activity").innerHTML=a.map(x=>`<div class="item"><b>${x.id} · ${esc(x.text)}</b><small>${esc(x.title)} · ${fmt(x.date)}</small></div>`).join("")||"<p class=muted>Sin actividad.</p>"}
function renderTickets(){let q=$("search").value.toLowerCase(),fs=$("fStatus").value,fp=$("fPriority").value;let t=vis().filter(x=>(!q||`${x.id} ${x.title} ${user(x.requester)?.name}`.toLowerCase().includes(q))&&(!fs||x.status===fs)&&(!fp||x.priority===fp)).sort((a,b)=>new Date(b.updated)-new Date(a.updated));$("ticketRows").innerHTML=t.map(x=>`<tr><td><b>${x.id}</b></td><td>${esc(x.title)}</td><td>${esc(x.category)}</td><td>${badge(x.priority,"priority")}</td><td>${badge(x.status,"status")}</td><td>${esc(user(x.requester)?.name||"—")}</td><td>${esc(user(x.assigned)?.name||"Sin asignar")}</td><td><button onclick="detail('${x.id}')">Ver</button></td></tr>`).join("")}
function renderUsers(){if(!me||me.role!=="Administrador")return;$("userRows").innerHTML=data.users.map(u=>`<tr><td><b>${esc(u.name)}</b></td><td>${esc(u.email)}</td><td>${u.role}</td><td>${u.active?"Activo":"Inactivo"}</td><td>${u.id!==me.id?`<button onclick="toggleUser('${u.id}')">${u.active?"Desactivar":"Activar"}</button>`:"Sesión actual"}</td></tr>`).join("")}
window.toggleUser=id=>{let u=user(id);u.active=!u.active;save();renderUsers();toast("Usuario actualizado")}
function renderCategories(){$("categoryList").innerHTML=data.categories.map(c=>`<div class="item"><b>${esc(c.name)}</b><small>${esc(c.description)}</small>${me.role==="Administrador"?`<button onclick="delCat('${c.id}')">Eliminar</button>`:""}</div>`).join("")}
window.delCat=id=>{let c=data.categories.find(x=>x.id===id);if(data.tickets.some(t=>t.category===c.name))return toast("Categoría en uso");data.categories=data.categories.filter(x=>x.id!==id);save();renderCategories();renderOptions()}
function renderReports(){let t=vis(),r=t.filter(x=>["Resuelto","Cerrado"].includes(x.status)).length;$("metrics").innerHTML=[["Tickets visibles",t.length],["Tasa de resolución",t.length?Math.round(r/t.length*100)+"%":"0%"],["Críticos",t.filter(x=>x.priority==="Crítica").length],["Asignados",t.filter(x=>x.assigned).length],["Usuarios",data.users.length]].map(x=>`<div class="metric"><span>${x[0]}</span><b>${x[1]}</b></div>`).join("")}
function renderOptions(){$("tCategory").innerHTML=data.categories.map(c=>`<option>${esc(c.name)}</option>`).join("");$("tAssigned").innerHTML='<option value="">Sin asignar</option>'+data.users.filter(u=>u.active&&["Administrador","Técnico"].includes(u.role)).map(u=>`<option value="${u.id}">${esc(u.name)} · ${u.role}</option>`).join("")}
function openModal(id){$(id).classList.remove("hidden")}function closeModal(id){$(id).classList.add("hidden")}
function openTicket(id=""){$("ticketForm").reset();$("ticketId").value="";renderOptions();$("ticketModalTitle").textContent=id?"Editar ticket":"Nuevo ticket";if(id){let t=data.tickets.find(x=>x.id===id);$("ticketId").value=t.id;$("tTitle").value=t.title;$("tCategory").value=t.category;$("tPriority").value=t.priority;$("tDescription").value=t.description;$("tAssigned").value=t.assigned||"";$("tStatus").value=t.status}all("#ticketModal .staff").forEach(x=>x.classList.toggle("hidden",me.role==="Usuario"));openModal("ticketModal")}
window.detail=id=>{selected=id;let t=data.tickets.find(x=>x.id===id);$("dTitle").textContent=`${t.id} · ${t.title}`;$("dMeta").textContent=`Creado ${fmt(t.created)} · Actualizado ${fmt(t.updated)}`;$("dBadges").innerHTML=badge(t.priority,"priority")+" "+badge(t.status,"status")+` <span class="badge assigned">${esc(t.category)}</span>`;$("dDescription").textContent=t.description;$("dInfo").innerHTML=[["Solicitante",user(t.requester)?.name||"—"],["Asignado",user(t.assigned)?.name||"Sin asignar"],["Estado",t.status],["Prioridad",t.priority]].map(x=>`<div class="metric"><span>${x[0]}</span><b>${esc(x[1])}</b></div>`).join("");$("comments").innerHTML=t.comments.slice().reverse().map(c=>`<div class="item"><b>${esc(user(c.user)?.name||"Usuario")}</b><small>${fmt(c.date)}</small><p>${esc(c.text)}</p></div>`).join("")||"<p class=muted>Sin comentarios.</p>";$("history").innerHTML=t.history.slice().reverse().map(h=>`<div class="item"><b>${esc(h.text)}</b><small>${esc(user(h.user)?.name||"Usuario")} · ${fmt(h.date)}</small></div>`).join("");all("#detailModal .admin").forEach(x=>x.classList.toggle("hidden",me.role!=="Administrador"));all("#detailModal .staff").forEach(x=>x.classList.toggle("hidden",me.role==="Usuario"));openModal("detailModal")}
$("loginForm").onsubmit=e=>{e.preventDefault();let u=data.users.find(x=>x.email.toLowerCase()===$("email").value.trim().toLowerCase()&&x.password===$("password").value&&x.active);if(!u)return toast("Credenciales incorrectas");me=u;localStorage.setItem(S,u.id);showApp()}
$("logout").onclick=()=>{localStorage.removeItem(S);location.reload()};all("nav button").forEach(b=>b.onclick=()=>nav(b.dataset.view));all("[data-close]").forEach(x=>x.onclick=()=>closeModal(x.dataset.close));$("newTicket").onclick=()=>openTicket();$("search").oninput=renderTickets;$("fStatus").onchange=renderTickets;$("fPriority").onchange=renderTickets;
$("ticketForm").onsubmit=e=>{e.preventDefault();let id=$("ticketId").value;if(id){let t=data.tickets.find(x=>x.id===id),old=t.status;t.title=$("tTitle").value;t.category=$("tCategory").value;t.priority=$("tPriority").value;t.description=$("tDescription").value;if(me.role!=="Usuario"){t.assigned=$("tAssigned").value;t.status=$("tStatus").value}t.updated=now();if(old!==t.status)t.history.push({user:me.id,text:"Estado cambiado a "+t.status,date:now()});t.history.push({user:me.id,text:"Ticket actualizado",date:now()})}else{let num=Math.max(1000,...data.tickets.map(t=>+t.id.replace(/\D/g,"")))+1;data.tickets.push({id:"TK-"+num,title:$("tTitle").value,description:$("tDescription").value,category:$("tCategory").value,priority:$("tPriority").value,status:me.role==="Usuario"?"Abierto":$("tStatus").value,requester:me.id,assigned:me.role==="Usuario"?"":$("tAssigned").value,created:now(),updated:now(),comments:[],history:[{user:me.id,text:"Ticket creado",date:now()}]})}save();closeModal("ticketModal");renderAll();toast("Ticket guardado")}
$("commentForm").onsubmit=e=>{e.preventDefault();let t=data.tickets.find(x=>x.id===selected),text=$("comment").value.trim();t.comments.push({user:me.id,text,date:now()});t.history.push({user:me.id,text:"Comentario agregado",date:now()});t.updated=now();$("comment").value="";save();renderAll();detail(t.id);toast("Comentario agregado")}
$("editTicket").onclick=()=>{closeModal("detailModal");openTicket(selected)};$("deleteTicket").onclick=()=>{if(me.role!=="Administrador"||!confirm("¿Eliminar ticket?"))return;data.tickets=data.tickets.filter(x=>x.id!==selected);save();closeModal("detailModal");renderAll()}
$("newUser").onclick=()=>openModal("userModal");$("userForm").onsubmit=e=>{e.preventDefault();let email=$("uEmail").value.trim().toLowerCase();if(data.users.some(u=>u.email.toLowerCase()===email))return toast("Correo ya registrado");data.users.push({id:"U"+(data.users.length+1),name:$("uName").value,email,password:$("uPass").value,role:$("uRole").value,active:true});save();e.target.reset();closeModal("userModal");renderAll();renderOptions()}
$("categoryForm").onsubmit=e=>{e.preventDefault();let n=$("catName").value.trim();if(data.categories.some(c=>c.name.toLowerCase()===n.toLowerCase()))return toast("Categoría ya existe");data.categories.push({id:"C"+(data.categories.length+1),name:n,description:$("catDesc").value.trim()});save();e.target.reset();renderCategories();renderOptions()}
function download(c,n,t){let a=document.createElement("a"),u=URL.createObjectURL(new Blob([c],{type:t}));a.href=u;a.download=n;a.click();URL.revokeObjectURL(u)}
$("csv").onclick=()=>{let r=[["ID","Asunto","Categoría","Prioridad","Estado","Solicitante","Asignado"]];vis().forEach(t=>r.push([t.id,t.title,t.category,t.priority,t.status,user(t.requester)?.name||"",user(t.assigned)?.name||""]));download(r.map(x=>x.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(",")).join("\\n"),"devtrack-tickets.csv","text/csv")}
$("json").onclick=()=>download(JSON.stringify(data,null,2),"devtrack-respaldo.json","application/json")
let sid=localStorage.getItem(S);me=sid?user(sid):null;if(me)showApp();
